---

- name: Install zabbix-server
  apt:
    name:
      - "zabbix-server-{% if zbx_database != 'timescaledb' %}{{ zbx_database }}{% else %}pgsql{% endif %}"
      - zabbix-get
      - zabbix-sender
    update_cache: yes
    cache_valid_time: 3600

- include_tasks: "{{ zbx_database }}.yml"

- name: zabbix_server.conf
  lineinfile:
    path: "/etc/zabbix/zabbix_server.conf"
    regexp: '#?{{ item.k }} =.*'
    line: '{{ item.k }} = {{ item.v }}'
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zbx_server_conf }}"
  register: zbx_conf

- name: Restart zabbix-server
  systemd:
    name: "zabbix-server.service"
    state: restarted
  when: zbx_conf is changed or zbx_db is changed
