---
# tasks file for egeneralov.zabbix-server

- import_tasks: check.yml
- import_tasks: install_server.yml
- import_tasks: install_frontend.yml

- name: place config for frontend
  template:
    src: zabbix.conf.php.j2
    dest: /usr/share/zabbix/conf/zabbix.conf.php
    mode: 0777

